# Materials selected by `cxr scan --all` and `cxr remote ... --all`.
materials = [
    "hopg",
    "hbn",
    "black_phosphorus",
    "fete",
    "hfs2",
    "hfse2",
    "hfte2",
    "gese",
    "gese2",
    "mos2",
    "mose2",
    "mote2",
    "nbs2",
    "nbse2",
    "nbte2",
    "pds2",
    "pdse2",
    "pdte2",
    "ptbi2",
    "pts2",
    "ptse2",
    "ptte2",
    "res2",
    "2h_tas2",
    "2h_tase2",
    "tate2",
    # "v2o5",
    "vse2",
    # "ws2",
    # "wse2",
    "wte2",
    "zrse2",
    "zrte3",
    "zrte5",
]

high_energy_materials = [
# ! --- Everything below is only worthwhile to sim for higher beam energies (e.g., 300 keV) --- ! #
    "tise2", # 100 keV and above
    "gep",
    "ges",
    "rese2",
]

materials_to_leave_out = [
    "diamond",
    "sapphire",
    "silicon",
    "4h_sic",
    "6h_sic",
    "tis2",
    "tite2",
    "vte2",
]
