"""Cross-check local crystal lattice geometry against an external database.

Guards ``issue_notes.md`` item #2: every catalog entry that pins an external
structure id (``cod_id`` / ``mp_id``) has its lattice ``(a, b, c, alpha, beta,
gamma)`` diffed against the authoritative record. This catches silent drift or
transcription error in the local CIFs.

Scope is **geometry only** -- see ``docs/crystal-db-comparison.md``. It does NOT
validate Debye-Waller factors (``issue_notes.md`` item #1): external databases
do not carry a reliable isotropic B.

Offline tests diff against a committed reference
(``tests/data/external_crystal_lattices.json``, regenerated by
``scripts/refresh_external_cif.py``). The ``online`` test re-fetches live from
COD/MP and is skipped unless ``CXR_ONLINE_TESTS=1``.
"""

from __future__ import annotations

import os

import pytest
from external_db_fixtures import (
    MP_API_KEY_ENV,
    TOL_ANGLE_DEG,
    TOL_COD_ANG,
    TOL_MP_REL,
    Lattice,
    cached_lattice_tuple,
    fetch_external,
    iter_specs_sorted,
    lattice_tuple,
    load_cached_lattices,
    local_lattice_tuple,
)

_ALL_SPECS = list(iter_specs_sorted())
_COD_SPECS = [(key, cod_id) for key, cod_id, _mp_id in _ALL_SPECS if cod_id is not None]
_CACHED = load_cached_lattices()

_RUN_ONLINE = os.environ.get("CXR_ONLINE_TESTS") == "1"


def _assert_lengths_close(local: Lattice, other: Lattice, *, rel: bool, tol: float) -> None:
    for name, lv, ov in zip(("a", "b", "c"), local[:3], other[:3], strict=True):
        delta = abs(lv - ov)
        bound = tol * ov if rel else tol
        assert delta <= bound, (
            f"lattice length {name}: local {lv:.5f} vs external {ov:.5f} "
            f"(|Δ|={delta:.2e} > {bound:.2e})"
        )


def _assert_angles_close(local: Lattice, other: Lattice, tol: float) -> None:
    for name, lv, ov in zip(("alpha", "beta", "gamma"), local[3:], other[3:], strict=True):
        delta = abs(lv - ov)
        assert delta <= tol, (
            f"lattice angle {name}: local {lv:.4f}° vs external {ov:.4f}° "
            f"(|Δ|={delta:.2e} > {tol:.2e})"
        )


def _assert_geometry_agrees(local: Lattice, other: Lattice, *, source: str) -> None:
    """Compare two lattices with a tolerance keyed to the external source."""
    if source.startswith("mp"):
        # DFT-relaxed cell: relative length tolerance, slightly looser angles.
        _assert_lengths_close(local, other, rel=True, tol=TOL_MP_REL)
        _assert_angles_close(local, other, max(TOL_ANGLE_DEG, 1.0))
    else:
        # Experimental COD cell: tight absolute tolerance.
        _assert_lengths_close(local, other, rel=False, tol=TOL_COD_ANG)
        _assert_angles_close(local, other, TOL_ANGLE_DEG)


def test_external_ids_are_present() -> None:
    """The catalog pins at least the known COD-backed entries."""
    assert _COD_SPECS, "no crystals carry a cod_id; metadata backfill missing"


def test_cached_reference_covers_every_cod_entry() -> None:
    """No COD-pinned crystal is missing from the committed reference, and the
    reference has no orphan entries. Keeps fixture and catalog in lockstep."""
    cod_keys = {key for key, _ in _COD_SPECS}
    cached_keys = set(_CACHED)
    missing = sorted(cod_keys - cached_keys)
    orphan = sorted(cached_keys - {key for key, _c, _m in _ALL_SPECS})
    assert not missing, f"run scripts/refresh_external_cif.py; missing cached lattices: {missing}"
    assert not orphan, f"stale cached lattices with no catalog id: {orphan}"


@pytest.mark.parametrize(("key", "cod_id"), _COD_SPECS, ids=[k for k, _ in _COD_SPECS])
def test_local_lattice_matches_cached_cod(key: str, cod_id: int) -> None:
    """Local lattice agrees with the pinned COD reference (offline)."""
    entry = _CACHED.get(key)
    assert entry is not None, (
        f"missing cached lattice for {key}; run scripts/refresh_external_cif.py"
    )
    local = local_lattice_tuple(key)
    external = cached_lattice_tuple(entry)
    _assert_geometry_agrees(local, external, source=str(entry.get("source", "cod")))


@pytest.mark.online
@pytest.mark.skipif(
    not _RUN_ONLINE, reason="set CXR_ONLINE_TESTS=1 to run external-DB network tests"
)
@pytest.mark.parametrize(
    ("key", "cod_id", "mp_id"), _ALL_SPECS, ids=[k for k, _c, _m in _ALL_SPECS]
)
def test_local_lattice_matches_live_external(
    key: str, cod_id: int | None, mp_id: str | None
) -> None:
    """Re-fetch the external record live and diff against the local catalog.

    Also catches drift in the committed reference itself. MP entries skip when
    no API key is configured.
    """
    crystal = fetch_external(cod_id, mp_id)
    if crystal is None:
        pytest.skip(f"{key}: mp-only entry and no {MP_API_KEY_ENV} set")
    live = lattice_tuple(crystal)
    local = local_lattice_tuple(key)
    source = f"cod:{cod_id}" if cod_id is not None else f"mp:{mp_id}"
    _assert_geometry_agrees(local, live, source=source)
