"""Generate or check the Click command reference.

Usage:
    uv run pyrite-dev cli-reference --write
    uv run pyrite-dev cli-reference --check
"""

import argparse
import re
from pathlib import Path

import click

from pyrite import __version__
from pyrite.cli import command


def _context(
    current: click.Command,
    name: str,
    parent: click.Context | None = None,
) -> click.Context:
    settings = dict(current.context_settings or {})
    settings.update(
        terminal_width=88,
        max_content_width=88,
        color=False,
    )
    return click.Context(
        current,
        info_name=name,
        parent=parent,
        **settings,
    )


def _walk(
    current: click.Command,
    path: tuple[str, ...],
    parent: click.Context | None = None,
):
    ctx = _context(current, path[-1], parent)
    yield path, current, ctx
    if isinstance(current, click.Group):
        for name in current.list_commands(ctx):
            child = current.get_command(ctx, name)
            if child is None:
                raise RuntimeError(
                    f"command disappeared while generating reference: {' '.join(path)} {name}"
                )
            if child.hidden:
                continue
            yield from _walk(child, (*path, name), ctx)


ANSI_ESCAPE = re.compile(r"\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])")


def build_reference() -> str:
    nodes = list(_walk(command, ("pyrite",)))
    lines = [
        "# `pyrite` CLI reference",
        "",
        f"Version: `{__version__}`",
        "",
        "<!-- Generated by pyrite-dev cli-reference --write; do not edit by hand. -->",
        "",
        "Current command reference generated from live Click definitions. See",
        "[README](https://github.com/Quantum-Light-Matter-Cooperative-QLMC/pyrite#readme) for scientific workflow,",
        "[cluster guide](../../guides/running-on-a-cluster.md) for scheduler templates,",
        "[repository map](../../repo_map.md) for implementation ownership, and",
        "[deprecations](cli-deprecations.md) for retired-spelling replacements and",
        "removal versions. Regenerate this page with `pyrite-dev cli-reference --write`.",
        "",
        "Remote lab defaults: `--chunk-minutes 10` runs one material at a time in",
        "self-resubmitting slices. `--chunk-minutes 0` selects one monolithic",
        "`UNLIMITED` allocation; that mode defaults to one material process and",
        "accepts at most four. Context-backed values use one precedence chain:",
        "per-call flag, then `PYRITE_*`, then the config store, then the built-in",
        "default. `PYRITE_PROFILE` and `PYRITE_REMOTE_HOST` are the environment tiers.",
        "`pyrite run PROFILE --remote` runs the profile membership; `-m MATERIAL`",
        "narrows it to one material. Compute-performance measurement is isolated",
        "behind `pyrite-dev perf PROFILE`; it accepts the same selectors.",
        "",
        "Checkpoint operations use the grouped `pyrite checkpoint ...` paths. The",
        "top-level `slim`, `rebrem`, `reline`, `archive`, `restore`, `archives`,",
        "and `union` spellings were removed at 0.3.0 and now exit as unknown",
        "commands.",
        "",
        "Validation uses `pyrite app validation` and `pyrite material validate`; the",
        "Zhai reproduction uses `pyrite run --preset zhai`, which runs locally unless",
        "`--remote` is given. Remote runs use",
        "`pyrite run --remote`. The `check`, `check-config`, `remote run`,",
        "`remote validate`, and `remote check` spellings were removed at 0.3.0.",
        "Energy-grid job lifecycle uses the top-level `pyrite job ...` paths; the",
        "former `pyrite energy-grid` job paths were removed at the same time.",
        "User grid derivation and inspection live below `pyrite material energy-grid`;",
        "profile derivation defaults live below `pyrite profile energy-grid`.",
        "Artifact mutation and verification use `pyrite-dev energy-grid`.",
        "",
        "`pyrite profile` writes your profiles to the user catalog layer",
        "(`catalog.user`, the platform config directory by default) and treats the",
        "bundled demo profiles as read-only; `pyrite-dev profile` is the same tree",
        "for maintainers editing the shipped demos.",
        "",
        "Automation contract: usage errors exit 2; runtime failures exit 1;",
        "interrupted viewers exit 130; resumable compute exits 75. Diagnostics,",
        "warnings, prompts, and progress use stderr. `-o/--output json` emits one UTF-8",
        "object plus newline with `schema`, `schema_version`, `ok`, `payload`,",
        "and `errors` fields and no human prose on stdout. `table` is the human",
        "default; `wide` is human-only and not a stable automation contract.",
        "",
        "Destructive commands preview exact targets by default. In a TTY, accept the",
        "`[y/N]` prompt to execute; in non-interactive use, pass `-y/--yes`.",
        "`pyrite job stop` requires JOBID or an explicit selector.",
        "",
        "Commands below are authoritative for this version.",
        "",
        "## Command tree",
        "",
    ]

    for path, current, ctx in nodes:
        title = " ".join(path)

        # Get raw help text from Click or any styling wrapper
        raw_help = current.get_help(ctx).rstrip()

        # Strip any stubborn ANSI codes out of the help text strings
        clean_help = ANSI_ESCAPE.sub("", raw_help)

        lines.extend(
            [
                f"## `{title}`",
                "",
                "```text",
                clean_help,  # <-- Use the cleaned text here
                "```",
                "",
            ]
        )
    return "\n".join(lines)
    for path, current, _ctx in nodes:
        if len(path) == 1:
            continue
        indent = "  " * (len(path) - 2)
        summary = current.get_short_help_str(limit=100)
        lines.append(f"{indent}- `{' '.join(path)}` — {summary}")
    lines.append("")
    for path, current, ctx in nodes:
        title = " ".join(path)
        lines.extend(
            [
                f"## `{title}`",
                "",
                "```text",
                current.get_help(ctx).rstrip(),
                "```",
                "",
            ]
        )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", type=Path, metavar="PATH")
    mode.add_argument("--check", type=Path, metavar="PATH")
    args = parser.parse_args(argv)
    encoded = build_reference()
    target = args.write or args.check
    assert target is not None
    if args.write is not None:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(encoded, encoding="utf-8")
        return 0
    if target.read_text(encoding="utf-8") != encoded:
        parser.error(f"CLI reference changed: regenerate with --write {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
