"""Generate compact views of the detailed physics-validation ledger."""

import ast
import re
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

from pyrite.validation.check_records import ValidationRecord, read_records

STATUS_ORDER = (
    "signed-off",
    "anchored",
    "rederived",
    "filtered",
    "unverified",
    "discrepancy",
)
GENERATED_NOTICE = "<!-- Generated by pyrite-dev validation-ledger; do not edit. -->"
_DOMAIN = re.compile(r"^# (?P<domain>.+)$")
_RECORD = re.compile(r"^## `(?P<id>[^`]+)`$")
_PART_GLOB = "ledger-*.md"
_FIELD = re.compile(
    r"^- \*\*(?P<label>Claim|Code|Source|Status|Checks|Anchor|Notes):\*\* "
    r"(?P<value>.+)$"
)
_FIELD_ORDER = ("claim", "code", "source", "status", "checks", "anchor", "notes")


@dataclass(frozen=True)
class LedgerEntry:
    """One detailed ledger record and its owning domain heading."""

    domain: str
    validation_id: str
    claim: str
    code: str
    source: str
    status: str
    checks: str
    anchor: str
    notes: str
    part: str = ""


def parse_ledger(text: str, part: str = "") -> tuple[LedgerEntry, ...]:
    """Parse the records of one ledger part, whose title heading is the domain."""
    domain: str | None = None
    entries: list[LedgerEntry] = []
    validation_id: str | None = None
    fields: dict[str, str] = {}

    def finish_record() -> None:
        nonlocal validation_id, fields
        if validation_id is None:
            return
        missing = [name for name in _FIELD_ORDER if name not in fields]
        if missing:
            raise ValueError(
                f"malformed ledger record for {validation_id}: missing " + ", ".join(missing)
            )
        status = fields["status"]
        if status not in STATUS_ORDER:
            raise ValueError(
                f"malformed ledger record for {validation_id}: invalid status {status}"
            )
        assert domain is not None
        entries.append(
            LedgerEntry(
                domain=domain,
                validation_id=validation_id,
                claim=fields["claim"].replace(r"\|", "|"),
                code=fields["code"],
                source=fields["source"],
                status=status,
                checks=fields["checks"],
                anchor=fields["anchor"],
                notes=fields["notes"],
                part=part,
            )
        )
        validation_id = None
        fields = {}

    for line in text.splitlines():
        domain_match = _DOMAIN.match(line)
        if domain_match:
            finish_record()
            domain = domain_match.group("domain").strip()
            continue
        record_match = _RECORD.match(line)
        if record_match:
            finish_record()
            if domain is None:
                raise ValueError("ledger record appears before a domain heading")
            validation_id = record_match.group("id")
            continue
        field_match = _FIELD.match(line)
        if not field_match:
            continue
        if validation_id is None:
            raise ValueError("ledger field appears outside a record")
        label = field_match.group("label").lower()
        if label in fields:
            raise ValueError(f"duplicate {label} field for {validation_id}")
        fields[label] = field_match.group("value").strip()
    finish_record()
    if not entries:
        raise ValueError("ledger contains no records")
    _reject_duplicate_ids(entries)
    return tuple(entries)


def part_paths(index: Path) -> tuple[Path, ...]:
    """Return the ledger part files in the order the index toctree lists them."""
    listed = [
        line.strip()
        for line in index.read_text(encoding="utf-8").splitlines()
        if line.strip().startswith("ledger-")
    ]
    paths = [index.with_name(f"{name}.md") for name in listed]
    missing = [path.name for path in paths if not path.is_file()]
    if missing:
        raise ValueError(f"ledger index lists missing parts: {', '.join(missing)}")
    unlisted = sorted(path.name for path in index.parent.glob(_PART_GLOB) if path not in set(paths))
    if unlisted:
        raise ValueError(f"ledger parts missing from the index toctree: {', '.join(unlisted)}")
    return tuple(paths)


def parse_ledger_parts(index: Path) -> tuple[LedgerEntry, ...]:
    """Parse every ledger part of an index into one ordered entry sequence."""
    entries: list[LedgerEntry] = []
    for path in part_paths(index):
        entries.extend(parse_ledger(path.read_text(encoding="utf-8"), part=path.name))
    _reject_duplicate_ids(entries)
    return tuple(entries)


def _reject_duplicate_ids(entries: list[LedgerEntry]) -> None:
    """Raise if any validation ID appears more than once."""
    duplicate_ids = sorted(
        validation_id
        for validation_id, count in Counter(e.validation_id for e in entries).items()
        if count > 1
    )
    if duplicate_ids:
        raise ValueError(f"duplicate validation IDs: {', '.join(duplicate_ids)}")


def render_status_summary(
    entries: tuple[LedgerEntry, ...], records: tuple[ValidationRecord, ...] = ()
) -> str:
    """Render the compact project-level status view."""
    counts = Counter(entry.status for entry in entries)
    rows = [
        "| Status | Claims |",
        "|---|---:|",
        *(f"| `{status}` | {counts[status]} |" for status in STATUS_ORDER),
        f"| **Total** | **{len(entries)}** |",
    ]
    signed = counts["signed-off"]
    latest: dict[tuple[str, str], ValidationRecord] = {}
    for record in records:
        key = (record.ledger_id, record.check)
        previous = latest.get(key)
        if previous is None or record.recorded_at > previous.recorded_at:
            latest[key] = record
    verdicts_by_claim: dict[str, set[str]] = {}
    for record in latest.values():
        verdicts_by_claim.setdefault(record.ledger_id, set()).add(record.verdict)

    def claim_verdict(validation_id: str) -> str:
        verdicts = verdicts_by_claim.get(validation_id, set())
        return next(
            (verdict for verdict in ("fail", "pass", "skip") if verdict in verdicts),
            "missing",
        )

    evidence = Counter(claim_verdict(entry.validation_id) for entry in entries)
    dated = [record.recorded_at for record in latest.values()]
    oldest_evidence = min(dated) if dated else "—"
    return "\n".join(
        [
            GENERATED_NOTICE,
            "",
            "# Validation status summary",
            "",
            "Compact generated view of the [detailed validation ledger] (physics-validation-ledger.md). Regenerate with `pyrite-dev validation-ledger --write` after editing detailed records.",
            "",
            f"**Publication gate:** {signed} / {len(entries)} claims signed off.",
            "",
            "## Latest automated evidence",
            "",
            "| Verdict | Claims |",
            "|---|---:|",
            *(
                f"| `{verdict}` | {evidence[verdict]} |"
                for verdict in ("pass", "fail", "skip", "missing")
            ),
            "",
            f"Oldest current automated evidence: `{oldest_evidence}` (UTC timestamp; use it to assess evidence age).",
            "",
            *rows,
            "",
            "Status meanings and promotion rules are defined in the [validation methodology](methodology.md).",
            "",
        ]
    )


def render_domain_inventories(entries: tuple[LedgerEntry, ...]) -> str:
    """Render compact per-domain inventories linked to detailed records."""
    domains: dict[str, list[LedgerEntry]] = {}
    for entry in entries:
        domains.setdefault(entry.domain, []).append(entry)
    lines = [
        GENERATED_NOTICE,
        "",
        "# Validation domain inventories",
        "",
        "Generated browsing views of every claim in the [detailed validation ledger] (physics-validation-ledger.md). The detailed record remains authoritative.",
        "",
    ]
    for domain, domain_entries in domains.items():
        lines.extend(
            [
                f"## {domain}",
                "",
                "| ID | Claim | Status |",
                "|---|---|---|",
            ]
        )
        for entry in domain_entries:
            claim = entry.claim.replace("|", r"\|")
            lines.append(
                f"| [`{entry.validation_id}`]({entry.part}#{entry.validation_id}) "
                f"| {claim} | `{entry.status}` |"
            )
        lines.append("")
    return "\n".join(lines)


def generated_views(ledger: Path) -> dict[Path, str]:
    """Return generated output paths and their expected contents."""
    entries = parse_ledger_parts(ledger)
    records = read_records(ledger.with_name("check-records"))
    return {
        ledger.with_name("status-summary.md"): render_status_summary(entries, records),
        ledger.with_name("domain-inventories.md"): render_domain_inventories(entries),
    }


def write_or_check(ledger: Path, *, check: bool) -> bool:
    """Write generated views, or return whether both are current."""
    expected = generated_views(ledger)
    current = all(
        path.is_file() and path.read_text(encoding="utf-8") == content
        for path, content in expected.items()
    )
    if check:
        return current
    for path, content in expected.items():
        path.write_text(content, encoding="utf-8")
    return True


def python_anchors(code: str) -> tuple[tuple[str, str], ...]:
    """Extract Python owners, including file/symbol brace and shorthand lists.

    Bare Python files denote module owners. Catalog, research and proposed
    records have no Python owners. Measurement records name the check before
    ``against``; the remaining references are the system being measured.
    """
    if code.startswith("measurement only"):
        code = code.split(" against ", 1)[0]
    anchors: list[tuple[str, str]] = []
    current = ""
    for token in re.findall(r"`([^`]+)`", code):
        path, separator, names = token.partition("::")
        if path:
            file_group = re.fullmatch(r"(.*/)?\{([^{}]+)\}", path)
            if file_group and not separator:
                prefix = file_group.group(1) or ""
                anchors.extend(
                    (prefix + filename.strip(), "")
                    for filename in file_group.group(2).split(",")
                    if filename.strip().endswith(".py")
                )
                current = ""
                continue
            if not path.endswith(".py"):
                continue
            current = path
        elif not separator or not current:
            continue
        if separator:
            anchors.extend((current, name.strip()) for name in names.strip("{}").split(","))
        else:
            anchors.append((current, ""))
    return tuple(anchors)


_PythonOwner = ast.Module | ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef


def _python_symbols(tree: ast.Module) -> dict[str, _PythonOwner]:
    symbols: dict[str, _PythonOwner] = {"": tree}

    def visit(node: ast.AST, prefix: str = "") -> None:
        for child in ast.iter_child_nodes(node):
            if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                name = prefix + child.name
                symbols[name] = child
                visit(child, name + ".")
            elif (
                isinstance(node, ast.ClassDef)
                and isinstance(child, ast.AnnAssign)
                and isinstance(child.target, ast.Name)
            ):
                # Dataclass fields carry their marker on the owning class.
                symbols[prefix + child.target.id] = node
            elif not isinstance(child, (ast.expr, ast.arguments)):
                visit(child, prefix)

    visit(tree)
    return symbols


def marker_ids(docstring: str) -> set[str]:
    """Read comma-separated markers, including wrapped continuation lines."""
    return {
        validation_id
        for marker in re.finditer(r"Validation:\s*([a-z0-9-]+(?:,\s*[a-z0-9-]+)*)", docstring)
        for validation_id in re.split(r",\s*", marker.group(1))
    }


def marker_coverage_errors(entries: tuple[LedgerEntry, ...], root: Path) -> tuple[str, ...]:
    """Audit ledger owners without importing physics or optional GPU modules."""
    errors: list[str] = []
    cache: dict[Path, dict[str, _PythonOwner]] = {}
    for entry in entries:
        for filename, name in python_anchors(entry.code):
            path = root / filename
            if not path.is_file():
                path = root / "src" / "pyrite" / filename
            anchor = f"{filename}::{name}" if name else filename
            if not path.is_file():
                errors.append(f"{entry.validation_id}: missing file {anchor}")
                continue
            if path not in cache:
                cache[path] = _python_symbols(ast.parse(path.read_text(encoding="utf-8")))
            node = cache[path].get(name)
            if node is None:
                errors.append(f"{entry.validation_id}: missing definition {anchor}")
                continue
            if entry.validation_id not in marker_ids(ast.get_docstring(node) or ""):
                errors.append(f"{entry.validation_id}: missing marker on {anchor}")
    return tuple(errors)
