# Geant4 TestEm5, v11.4.2 (commit 8cc04f65977807f1848da7b958c421cd5e162f26).
# A 300 keV electron pencil beam in 10 um W, 19.3 g/cm3.
/control/verbose 0
/run/verbose 0
/run/numberOfThreads 1
/random/setSeeds 12345 67890
/testem/det/setAbsMat Tungsten
/testem/det/setAbsThick 10 um
/testem/det/setAbsYZ 1 cm
/testem/phys/addPhysics emstandardSS
/process/em/setSingleScattering DPWA
/process/eLoss/fluct false
/process/em/fluo false
/process/em/lowestElectronEnergy 10 keV
/run/setCut 1 nm
/run/setCutForAGivenParticle e- 1 mm
/run/initialize
/testem/gun/setDefault
/gun/particle e-
/gun/energy 300 keV
/analysis/setFileName w_300kev_ssdpwa
/analysis/h1/set 3 30 0 300 keV
/analysis/h1/setAscii 3
/analysis/h1/set 62 30 0 300 keV
/analysis/h1/setAscii 62
/run/beamOn 100000
