"""Generate or check the Click command reference.

Usage:
    python scripts/generate_cli_reference.py --write docs/cli-reference.md
    python scripts/generate_cli_reference.py --check docs/cli-reference.md
"""

from __future__ import annotations

import argparse
from pathlib import Path

import click

from cxr_mc import __version__
from cxr_mc.cli import command


def _context(
    current: click.Command,
    name: str,
    parent: click.Context | None = None,
) -> click.Context:
    return click.Context(
        current,
        info_name=name,
        parent=parent,
        terminal_width=88,
        max_content_width=88,
    )


def _walk(
    current: click.Command,
    path: tuple[str, ...],
    parent: click.Context | None = None,
):
    ctx = _context(current, path[-1], parent)
    yield path, current, ctx
    if isinstance(current, click.Group):
        for name in current.list_commands(ctx):
            child = current.get_command(ctx, name)
            if child is None:
                raise RuntimeError(
                    f"command disappeared while generating reference: {' '.join(path)} {name}"
                )
            yield from _walk(child, (*path, name), ctx)


def build_reference() -> str:
    nodes = list(_walk(command, ("cxr",)))
    lines = [
        "# `cxr` CLI reference",
        "",
        f"Version: `{__version__}`",
        "",
        "<!-- Generated by scripts/generate_cli_reference.py; do not edit by hand. -->",
        "",
        "Current command reference generated from live Click definitions. See",
        "[README](../README.md) for scientific workflow,",
        "[cluster guide](running-on-a-cluster.md) for scheduler templates, and",
        "[repository map](repo_map.md) for implementation ownership.",
        "",
        "Remote lab defaults: `--chunk-minutes 10` runs one material at a time in",
        "self-resubmitting slices. `--chunk-minutes 0` selects one monolithic",
        "`UNLIMITED` allocation; that mode defaults to two parallel materials and",
        "accepts at most four. `CXR_REMOTE_HOST`, `CXR_REMOTE_DIR`, and",
        "`CXR_REMOTE_UV` override configured connection values.",
        "",
        "Files under `docs/superpowers/plans/` and `docs/superpowers/specs/` are",
        "historical design records, not current CLI reference. Commands below are",
        "authoritative for this version.",
        "",
        "## Command tree",
        "",
    ]
    for path, current, _ctx in nodes:
        if len(path) == 1:
            continue
        indent = "  " * (len(path) - 2)
        summary = current.get_short_help_str(limit=100)
        lines.append(f"{indent}- `{' '.join(path)}` — {summary}")
    lines.append("")
    for path, current, ctx in nodes:
        title = " ".join(path)
        lines.extend(
            [
                f"## `{title}`",
                "",
                "```text",
                current.get_help(ctx).rstrip(),
                "```",
                "",
            ]
        )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", type=Path, metavar="PATH")
    mode.add_argument("--check", type=Path, metavar="PATH")
    args = parser.parse_args(argv)
    encoded = build_reference()
    target = args.write or args.check
    assert target is not None
    if args.write is not None:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(encoded, encoding="utf-8")
        return 0
    if target.read_text(encoding="utf-8") != encoded:
        parser.error(f"CLI reference changed: regenerate with --write {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
