"""Generate or check the Click command reference.

Usage:
    python scripts/generate_cli_reference.py --write docs/cli-reference.md
    python scripts/generate_cli_reference.py --check docs/cli-reference.md
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import click

from cxr_mc import __version__
from cxr_mc.cli import command


def _context(
    current: click.Command,
    name: str,
    parent: click.Context | None = None,
) -> click.Context:
    settings = dict(current.context_settings or {})
    settings.update(
        terminal_width=88,
        max_content_width=88,
        color=False,
    )
    return click.Context(
        current,
        info_name=name,
        parent=parent,
        **settings,
    )


def _walk(
    current: click.Command,
    path: tuple[str, ...],
    parent: click.Context | None = None,
):
    ctx = _context(current, path[-1], parent)
    yield path, current, ctx
    if isinstance(current, click.Group):
        for name in current.list_commands(ctx):
            child = current.get_command(ctx, name)
            if child is None:
                raise RuntimeError(
                    f"command disappeared while generating reference: {' '.join(path)} {name}"
                )
            if child.hidden:
                continue
            yield from _walk(child, (*path, name), ctx)


ANSI_ESCAPE = re.compile(r"\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])")


def build_reference() -> str:
    nodes = list(_walk(command, ("cxr",)))
    lines = [
        "# `cxr` CLI reference",
        "",
        f"Version: `{__version__}`",
        "",
        "<!-- Generated by scripts/generate_cli_reference.py; do not edit by hand. -->",
        "",
        "Current command reference generated from live Click definitions. See",
        "[README](https://github.com/Quantum-Light-Matter-Cooperative-QLMC/cxr-mc#readme) for scientific workflow,",
        "[cluster guide](running-on-a-cluster.md) for scheduler templates, and",
        "[repository map](repo_map.md) for implementation ownership.",
        "",
        "Remote lab defaults: `--chunk-minutes 10` runs one material at a time in",
        "self-resubmitting slices. `--chunk-minutes 0` selects one monolithic",
        "`UNLIMITED` allocation; that mode defaults to two parallel materials and",
        "accepts at most four. `CXR_REMOTE_HOST`, `CXR_REMOTE_DIR`, and",
        "`CXR_REMOTE_UV` override configured connection values.",
        "",
        "Checkpoint operations use the grouped `cxr checkpoint ...` paths. Legacy",
        "top-level `slim`, `rebrem`, `reline`, `archive`, `restore`, `archives`,",
        "and `union` paths remain callable compatibility aliases but are hidden",
        "from root help.",
        "",
        "Validation uses `cxr validate`, `cxr catalog validate`, and",
        "`cxr remote validate`. Legacy `check`, `check-config`, and remote",
        "`check` paths remain hidden compatibility aliases. Remote detached",
        "submission uses `cxr remote submit`; legacy `start` remains an alias.",
        "Energy-grid job lifecycle uses `cxr energy-grid job ...`; legacy flat job",
        "verbs remain aliases.",
        "",
        "Automation contract: usage errors exit 2; runtime failures exit 1;",
        "interrupted viewers exit 130; resumable compute exits 75. Diagnostics,",
        "warnings, prompts, and progress use stderr. `--json` emits one UTF-8",
        "object plus newline with `schema`, `schema_version`, `ok`, `payload`,",
        "and `errors` fields and no human prose on stdout.",
        "",
        "Destructive remote stop commands preview exact job targets by default.",
        "Pass `--yes` to perform cancellation; `cxr energy-grid stop` additionally",
        "requires JOBID or explicit `--latest`.",
        "",
        "Commands below are authoritative for this version.",
        "",
        "## Command tree",
        "",
    ]

    for path, current, ctx in nodes:
        title = " ".join(path)

        # Get raw help text from Click or any styling wrapper
        raw_help = current.get_help(ctx).rstrip()

        # Strip any stubborn ANSI codes out of the help text strings
        clean_help = ANSI_ESCAPE.sub("", raw_help)

        lines.extend(
            [
                f"## `{title}`",
                "",
                "```text",
                clean_help,  # <-- Use the cleaned text here
                "```",
                "",
            ]
        )
    return "\n".join(lines)
    for path, current, _ctx in nodes:
        if len(path) == 1:
            continue
        indent = "  " * (len(path) - 2)
        summary = current.get_short_help_str(limit=100)
        lines.append(f"{indent}- `{' '.join(path)}` — {summary}")
    lines.append("")
    for path, current, ctx in nodes:
        title = " ".join(path)
        lines.extend(
            [
                f"## `{title}`",
                "",
                "```text",
                current.get_help(ctx).rstrip(),
                "```",
                "",
            ]
        )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", type=Path, metavar="PATH")
    mode.add_argument("--check", type=Path, metavar="PATH")
    args = parser.parse_args(argv)
    encoded = build_reference()
    target = args.write or args.check
    assert target is not None
    if args.write is not None:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(encoded, encoding="utf-8")
        return 0
    if target.read_text(encoding="utf-8") != encoded:
        parser.error(f"CLI reference changed: regenerate with --write {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
