"""Generate or check the CLI deprecation table.

Usage:
    python scripts/generate_cli_deprecations.py --write docs/repo-design/cli/cli-deprecations.md
    python scripts/generate_cli_deprecations.py --check docs/repo-design/cli/cli-deprecations.md
"""

from __future__ import annotations

import argparse
from pathlib import Path

from cxr_mc import __version__
from cxr_mc.cli._deprecations import DEPRECATED_FLAGS, DEPRECATIONS, SUPPORT_WINDOW_MINORS


def build_deprecations() -> str:
    lines = [
        "# `pyrite` deprecations",
        "",
        f"Version: `{__version__}`",
        "",
        "<!-- Generated by scripts/generate_cli_deprecations.py; do not edit by hand. -->",
        "",
        (
            "Per [ADR-0002](../../adr/0002-cli-surface-redesign.md), every renamed or retired `pyrite` "
            f"command or option keeps its old spelling working for a minimum of "
            f"{SUPPORT_WINDOW_MINORS} minor releases, warns on stderr naming the "
            "replacement, and is listed here with its removal target. See the "
            "[CLI reference](cli-reference.md) for the current command surface; regenerate "
            "this table with `pyrite-dev cli-deprecations`."
        ),
        "",
        "## Commands",
        "",
        "| Deprecated spelling | Replacement | Deprecated in | Remove in | Note |",
        "| --- | --- | --- | --- | --- |",
    ]
    for path in sorted(DEPRECATIONS):
        entry = DEPRECATIONS[path]
        lines.append(
            f"| `pyrite {entry.path}` | `{entry.replacement}` | {entry.deprecated_in} "
            f"| {entry.remove_in} | {entry.note} |"
        )
    lines.extend(
        (
            "",
            "## Options",
            "",
            "| Command | Deprecated option | Replacement | Deprecated in | Remove in | Note |",
            "| --- | --- | --- | --- | --- | --- |",
        )
    )
    for key in sorted(DEPRECATED_FLAGS):
        entry = DEPRECATED_FLAGS[key]
        lines.append(
            f"| `pyrite {entry.command}` | `{entry.flag}` | `{entry.replacement}` "
            f"| {entry.deprecated_in} | {entry.remove_in} | {entry.note} |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", type=Path, metavar="PATH")
    mode.add_argument("--check", type=Path, metavar="PATH")
    args = parser.parse_args(argv)
    encoded = build_deprecations()
    target = args.write or args.check
    assert target is not None
    if args.write is not None:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(encoded, encoding="utf-8")
        return 0
    if target.read_text(encoding="utf-8") != encoded:
        parser.error(f"CLI deprecations changed: regenerate with --write {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
