"""Generate the static package-dependency region in ``docs/repo_map.md``."""

from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path

import grimp

BEGIN = "<!-- BEGIN GENERATED PACKAGE DEPENDENCIES -->"
END = "<!-- END GENERATED PACKAGE DEPENDENCIES -->"
PACKAGE = "cxr_mc"


def _top_level_packages(source_root: Path) -> set[str]:
    package_root = source_root / PACKAGE
    return {
        child.name
        for child in package_root.iterdir()
        if child.is_dir() and (child / "__init__.py").is_file()
    }


def _owner(module: str, packages: set[str]) -> str | None:
    parts = module.split(".")
    if len(parts) >= 2 and parts[0] == PACKAGE and parts[1] in packages:
        return parts[1]
    return None


def package_dependencies(source_root: Path) -> tuple[set[str], set[tuple[str, str]]]:
    """Return canonical top-level packages and their direct static dependencies."""
    packages = _top_level_packages(source_root)
    graph = grimp.build_graph(
        PACKAGE,
        exclude_type_checking_imports=True,
        cache_dir=None,
    )
    edges: set[tuple[str, str]] = set()
    for importer in graph.modules:
        importer_owner = _owner(importer, packages)
        if importer_owner is None:
            continue
        if importer == f"{PACKAGE}.{importer_owner}":
            # Package facades intentionally re-export their public surface and
            # would otherwise turn ownership edges into artificial cycles.
            continue
        for imported in graph.find_modules_directly_imported_by(importer):
            imported_owner = _owner(imported, packages)
            if imported_owner is not None and imported_owner != importer_owner:
                edges.add((importer_owner, imported_owner))
    return packages, edges


def _strongly_connected_components(
    nodes: Iterable[str], edges: set[tuple[str, str]]
) -> list[tuple[str, ...]]:
    adjacency = {node: set() for node in nodes}
    for source, target in edges:
        adjacency[source].add(target)

    index = 0
    stack: list[str] = []
    indices: dict[str, int] = {}
    lowlinks: dict[str, int] = {}
    on_stack: set[str] = set()
    components: list[tuple[str, ...]] = []

    def visit(node: str) -> None:
        nonlocal index
        indices[node] = index
        lowlinks[node] = index
        index += 1
        stack.append(node)
        on_stack.add(node)
        for target in sorted(adjacency[node]):
            if target not in indices:
                visit(target)
                lowlinks[node] = min(lowlinks[node], lowlinks[target])
            elif target in on_stack:
                lowlinks[node] = min(lowlinks[node], indices[target])
        if lowlinks[node] != indices[node]:
            return
        component: list[str] = []
        while True:
            member = stack.pop()
            on_stack.remove(member)
            component.append(member)
            if member == node:
                break
        components.append(tuple(sorted(component)))

    for node in sorted(adjacency):
        if node not in indices:
            visit(node)
    return sorted(components)


def build_dependency_region(source_root: Path) -> str:
    packages, edges = package_dependencies(source_root)
    components = _strongly_connected_components(packages, edges)
    component_for = {member: component for component in components for member in component}
    component_id = {component: f"p{index}" for index, component in enumerate(components)}
    condensed_edges = {
        (component_for[source], component_for[target])
        for source, target in edges
        if component_for[source] != component_for[target]
    }

    lines = [
        BEGIN,
        "<!-- Generated by cxr_mc.devtools.repo_map; update with `cxr-dev repo-map --write`. -->",
        "",
        "Arrows point from importer to imported package. Strongly connected packages are",
        "collapsed into one node so this static condensation graph is a DAG. Imports hidden",
        "behind lazy dispatch, ``__getattr__``, or ``import_module`` are outside this scan.",
        "",
        "```text",
        "Components (a + b denotes a static import cycle):",
    ]
    for component in components:
        label = " + ".join(component)
        lines.append(f"  {component_id[component]}: {label}")
    lines.append("Edges (importer -> imported):")
    for source, target in sorted(
        condensed_edges,
        key=lambda edge: (component_id[edge[0]], component_id[edge[1]]),
    ):
        lines.append(f"  {component_id[source]} -> {component_id[target]}")
    lines.extend(["```", END])
    return "\n".join(lines)


def update_repo_map(document: str, generated: str) -> str:
    if document.count(BEGIN) != 1 or document.count(END) != 1:
        raise ValueError(f"repository map must contain exactly one {BEGIN!r}/{END!r} region")
    prefix, remainder = document.split(BEGIN, 1)
    _, suffix = remainder.split(END, 1)
    return f"{prefix}{generated}{suffix}"


def write_or_check(*, root: Path, check: bool) -> bool:
    target = root / "docs" / "repo_map.md"
    expected = update_repo_map(
        target.read_text(encoding="utf-8"),
        build_dependency_region(root / "src"),
    )
    if check:
        return target.read_text(encoding="utf-8") == expected
    target.write_text(expected, encoding="utf-8")
    return True
