"""Generate compact views of the detailed physics-validation ledger."""

from __future__ import annotations

import re
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

STATUS_ORDER = (
    "signed-off",
    "anchored",
    "rederived",
    "filtered",
    "unverified",
    "blocked",
    "discrepancy",
)
GENERATED_NOTICE = "<!-- Generated by pyrite-dev validation-ledger; do not edit. -->"
_ROW = re.compile(r"^\| `(?P<id>[^`]+)` \|")
_STATUS_CELL = re.compile(r" \| (" + "|".join(STATUS_ORDER) + r") \|")


@dataclass(frozen=True)
class LedgerEntry:
    """One detailed ledger row and its owning domain heading."""

    domain: str
    validation_id: str
    claim: str
    status: str


def parse_ledger(text: str) -> tuple[LedgerEntry, ...]:
    """Parse domain, ID, claim, and status from the canonical Markdown ledger."""
    domain: str | None = None
    entries: list[LedgerEntry] = []
    for line in text.splitlines():
        if line.startswith("## "):
            domain = line.removeprefix("## ").strip()
            continue
        if not _ROW.match(line):
            continue
        if domain is None:
            raise ValueError("ledger row appears before a domain heading")
        match = _ROW.match(line)
        assert match is not None
        validation_id = match.group("id")
        remainder = line[match.end() :]
        claim, separator, _ = remainder.partition(" | ")
        status_match = _STATUS_CELL.search(line)
        if not separator or status_match is None:
            raise ValueError(f"malformed ledger row for {validation_id}")
        entries.append(
            LedgerEntry(
                domain,
                validation_id,
                claim.strip().replace(r"\|", "|"),
                status_match.group(1),
            )
        )
    if not entries:
        raise ValueError("ledger contains no records")
    duplicate_ids = sorted(
        validation_id
        for validation_id, count in Counter(e.validation_id for e in entries).items()
        if count > 1
    )
    if duplicate_ids:
        raise ValueError(f"duplicate validation IDs: {', '.join(duplicate_ids)}")
    return tuple(entries)


def render_status_summary(entries: tuple[LedgerEntry, ...]) -> str:
    """Render the compact project-level status view."""
    counts = Counter(entry.status for entry in entries)
    rows = [
        "| Status | Claims |",
        "|---|---:|",
        *(f"| `{status}` | {counts[status]} |" for status in STATUS_ORDER),
        f"| **Total** | **{len(entries)}** |",
    ]
    signed = counts["signed-off"]
    return "\n".join(
        [
            GENERATED_NOTICE,
            "",
            "# Validation status summary",
            "",
            "Compact generated view of the [detailed validation ledger]",
            "(physics-validation-ledger.md). Regenerate with",
            "`pyrite-dev validation-ledger --write` after editing detailed records.",
            "",
            f"**Publication gate:** {signed} / {len(entries)} claims signed off.",
            "",
            *rows,
            "",
            "Status meanings and promotion rules are defined in the",
            "[validation methodology](methodology.md).",
            "",
        ]
    )


def render_domain_inventories(entries: tuple[LedgerEntry, ...]) -> str:
    """Render compact per-domain inventories linked to detailed records."""
    domains: dict[str, list[LedgerEntry]] = {}
    for entry in entries:
        domains.setdefault(entry.domain, []).append(entry)
    lines = [
        GENERATED_NOTICE,
        "",
        "# Validation domain inventories",
        "",
        "Generated browsing views of every claim in the [detailed validation ledger]",
        "(physics-validation-ledger.md). The detailed record remains authoritative.",
        "",
    ]
    for domain, domain_entries in domains.items():
        lines.extend(
            [
                f"## {domain}",
                "",
                "| ID | Claim | Status |",
                "|---|---|---|",
            ]
        )
        for entry in domain_entries:
            claim = entry.claim.replace("|", r"\|")
            lines.append(
                f"| [`{entry.validation_id}`](physics-validation-ledger.md) "
                f"| {claim} | `{entry.status}` |"
            )
        lines.append("")
    return "\n".join(lines)


def generated_views(ledger: Path) -> dict[Path, str]:
    """Return generated output paths and their expected contents."""
    entries = parse_ledger(ledger.read_text(encoding="utf-8"))
    return {
        ledger.with_name("status-summary.md"): render_status_summary(entries),
        ledger.with_name("domain-inventories.md"): render_domain_inventories(entries),
    }


def write_or_check(ledger: Path, *, check: bool) -> bool:
    """Write generated views, or return whether both are current."""
    expected = generated_views(ledger)
    current = all(
        path.is_file() and path.read_text(encoding="utf-8") == content
        for path, content in expected.items()
    )
    if check:
        return current
    for path, content in expected.items():
        path.write_text(content, encoding="utf-8")
    return True
